[package]
name = "diskord"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dirs = "6.0.0"
jwalk = "0.8.1"
ratatui = "0.30.0"
serde = "1.0.228"
serde_derive = "1.0.228"
sysinfo = "0.38.2"
toml = "1.0.3"
